// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CorporateDirectory1 {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("CustomCellController")]
	public partial class CustomCellController {
		
		[MonoTouch.Foundation.Connect("labelDepartment")]
		private MonoTouch.UIKit.UILabel labelDepartment {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelDepartment")));
			}
			set {
				this.SetNativeField("labelDepartment", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelName")]
		private MonoTouch.UIKit.UILabel labelName {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelName")));
			}
			set {
				this.SetNativeField("labelName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("cell")]
		private MonoTouch.UIKit.UITableViewCell cell {
			get {
				return ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("cell")));
			}
			set {
				this.SetNativeField("cell", value);
			}
		}
	}
}
